imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*, database/*]


build:
    environment:
        php: 8.0.2
        mysql: 5.7

        variables:
            APP_KEY: 'base64:p1Fjahal5lpQe8O+/EV9fMyYPbbVj/I5PI7tG33VOZ0='
            APP_ENV: 'testing'
            APP_URL: 'http://laravel.dev'
            DB_HOST: '127.0.0.1'
            DB_DATABASE: 'scrutinizer'
            DB_USERNAME: 'root'
            DB_PASSWORD: ''

    cache:
        directories:
            - vendor/
            - ~/.composer/cache/

    dependencies:
        before:
            - mysql -uroot -e 'CREATE DATABASE scrutinizer'

    tests:
        before:
            - mv .env.testing .env
            - php-scrutinizer-run
            - php artisan config:cache
            - php artisan key:generate
        
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=laravel-coverage
                coverage:
                    file: laravel-coverage
                    format: clover
