imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]


build:
    nodes:
        my-node:
            services:
                # For available tags, see https://hub.docker.com/_/mysql/
                mysql: 8.0

        my-tests:
            environment:
                php:
                    version: 8.1

        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            tests:
                before:
                    - mysql -uroot -e 'CREATE DATABASE scrutinizer'
                override:
                    -
                        command: "make phpunit"
                        coverage:
                            file: "build/coverage.clover"
                            format: "php-clover"
